### PR TITLE
Avoid last argument as keyword parameters deprecation warning mention…

### PR DESCRIPTION
**Pull request by thomasbalsloev**
…ed in issue #167

### CODE REVIEW

**Comment by thomasbalsloev** [comment]
Hi @cpjolicoeur 

Is this acceptable?

**Comment by joealba** [comment]
Thanks, @thomasbalsloev!  Your change works for me.  I've tested on Ruby 2.7 and Ruby 3.0.  

Updating `cucumber` and `rspec-given` fixes the failing tests and deprecation warnings. And adding `rexml` as an explicit dependency is needed for Ruby 3.0.  I will submit a PR to get those changes in today after your work is approved and merged.

Thanks again for the contribution!  Take care.

**Review by shoe — APPROVED** [review]

**Comment by shoe** [comment]
@thomasbalsloev Thanks!

**Comment by cpjolicoeur** [comment]
@thomasbalsloev [v1.3.0 has been released](https://rubygems.org/gems/capybara-ui/versions/1.3.0)

**Pull request merged**
